"""initial

Revision ID: 0001
Revises:
Create Date: 2026-08-06 17:46:57.157621
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("initial_cash", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("cash", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("paused_reason", sa.Text(), nullable=True),
        sa.Column("high_watermark", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("blocker", sa.Text(), nullable=True),
        sa.Column("input_versions", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agent_runs_kind_started", "agent_runs", ["kind", "started_at"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("actor", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_hash"),
    )
    op.create_table(
        "data_artifacts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("dataset", sa.String(length=80), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=False),
        sa.Column("min_date", sa.Date(), nullable=True),
        sa.Column("max_date", sa.Date(), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_artifacts_dataset", "data_artifacts", ["dataset", "sealed_at"], unique=False)
    op.create_table(
        "instruments",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("market", sa.String(length=20), nullable=False),
        sa.Column("exchange", sa.String(length=20), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("asset_type", sa.String(length=20), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("listed_on", sa.Date(), nullable=True),
        sa.Column("lot_size", sa.Integer(), nullable=False),
        sa.Column("tick_size", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("median_turnover_20d", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("investable", sa.Boolean(), nullable=False),
        sa.Column("exclusion_reason", sa.Text(), nullable=True),
        sa.Column("source_version", sa.String(length=80), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market", "exchange", "symbol", name="uq_instrument_identity"),
    )
    op.create_index("ix_instruments_investable", "instruments", ["investable", "asset_type"], unique=False)
    op.create_table(
        "lesson_candidates",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("week_ending", sa.Date(), nullable=False),
        sa.Column("scope", sa.String(length=80), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("supporting_experience_ids", sa.JSON(), nullable=False),
        sa.Column("contradicting_experience_ids", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "market_calendar_days",
        sa.Column("market", sa.String(length=20), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("market", "trade_date"),
    )
    op.create_table(
        "market_rule_versions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("market", sa.String(length=20), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "source_health",
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("role", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("source_id"),
    )
    op.create_table(
        "strategy_versions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column("rules", sa.JSON(), nullable=False),
        sa.Column("prompt_overrides", sa.JSON(), nullable=False),
        sa.Column("evidence_weights", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["strategy_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "user_feedback",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sentiment", sa.String(length=20), nullable=False),
        sa.Column("outcome_note", sa.Text(), nullable=True),
        sa.Column("used_for_challenger", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cash_ledger",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reference_type", sa.String(length=40), nullable=False),
        sa.Column("reference_id", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "challenger_reports",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("strategy_version_id", sa.String(length=64), nullable=False),
        sa.Column("champion_version_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=48), nullable=False),
        sa.Column("replay_case_count", sa.Integer(), nullable=False),
        sa.Column("shadow_days", sa.Integer(), nullable=False),
        sa.Column("net_excess_return", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("champion_excess_return", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("max_drawdown", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("champion_max_drawdown", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("calibration_score", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("champion_calibration_score", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("hard_risk_violations", sa.Integer(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["champion_version_id"],
            ["strategy_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence_refs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=True),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("credibility", sa.String(length=32), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_artifact_id", sa.String(length=64), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_artifact_id"],
            ["data_artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_evidence_instrument_published", "evidence_refs", ["instrument_id", "published_at"], unique=False
    )
    op.create_table(
        "intraday_trigger_states",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("call_count", sa.Integer(), nullable=False),
        sa.Column("last_called_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_price", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("last_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trade_date", "instrument_id", name="uq_trigger_day_symbol"),
    )
    op.create_table(
        "model_invocations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("purpose", sa.String(length=80), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_hash", sa.String(length=64), nullable=False),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cash", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("market_value", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("equity", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("drawdown", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("benchmark_value", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("positions", sa.JSON(), nullable=False),
        sa.Column("risk_state", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "research_dossiers",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("thesis", sa.JSON(), nullable=False),
        sa.Column("opposition", sa.JSON(), nullable=False),
        sa.Column("synthesis", sa.JSON(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("strategy_version_id", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("data_versions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_dossiers_instrument_created", "research_dossiers", ["instrument_id", "created_at"], unique=False
    )
    op.create_table(
        "decision_revisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("decision_key", sa.String(length=120), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.String(length=64), nullable=True),
        sa.Column("dossier_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("horizon", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("target_weight", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("expected_return_low", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("expected_return_high", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("probability_up", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("holding_days", sa.Integer(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("risks", sa.JSON(), nullable=False),
        sa.Column("trigger_reason", sa.Text(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("strategy_version_id", sa.String(length=64), nullable=False),
        sa.Column("risk_version", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["research_dossiers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["decision_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("decision_key", "revision", name="uq_decision_revision"),
    )
    op.create_index(
        "ix_decisions_instrument_horizon",
        "decision_revisions",
        ["instrument_id", "horizon", "created_at"],
        unique=False,
    )
    op.create_table(
        "experiences",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_version_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("horizon", sa.String(length=20), nullable=False),
        sa.Column("market_regime", sa.String(length=80), nullable=False),
        sa.Column("event_types", sa.JSON(), nullable=False),
        sa.Column("thesis_summary", sa.Text(), nullable=False),
        sa.Column("outcome_date", sa.Date(), nullable=False),
        sa.Column("net_return", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("benchmark_return", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("excess_return", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("direction_hit", sa.Boolean(), nullable=False),
        sa.Column("brier_score", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("max_favorable_excursion", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("max_adverse_excursion", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("attribution", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decision_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("decision_id"),
    )
    op.create_index("ix_experience_horizon_outcome", "experiences", ["horizon", "outcome_date"], unique=False)
    op.create_table(
        "order_plans",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("horizon", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("order_type", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("filled_quantity", sa.Integer(), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("blocked_reason", sa.Text(), nullable=True),
        sa.Column("eligible_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decision_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_orders_status_created", "order_plans", ["status", "created_at"], unique=False)
    op.create_table(
        "paper_fills",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("horizon", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("reference_price", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("fill_price", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("commission", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("tax", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("slippage_bps", sa.Integer(), nullable=False),
        sa.Column("bar_artifact_id", sa.String(length=64), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bar_artifact_id"],
            ["data_artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "position_lots",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("horizon", sa.String(length=20), nullable=False),
        sa.Column("opened_fill_id", sa.String(length=64), nullable=False),
        sa.Column("opened_trade_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("remaining_quantity", sa.Integer(), nullable=False),
        sa.Column("cost_price", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opened_fill_id"],
            ["paper_fills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_position_lots_account_instrument", "position_lots", ["account_id", "instrument_id"], unique=False
    )
    op.execute(
        "CREATE VIRTUAL TABLE experiences_fts USING fts5("
        "thesis_summary, tags, market_regime, content='experiences', content_rowid='rowid', tokenize='trigram')"
    )
    op.execute(
        "CREATE TRIGGER experiences_fts_insert AFTER INSERT ON experiences BEGIN "
        "INSERT INTO experiences_fts(rowid, thesis_summary, tags, market_regime) "
        "VALUES (new.rowid, new.thesis_summary, new.tags, new.market_regime); END"
    )
    immutable_tables = (
        "audit_events",
        "cash_ledger",
        "data_artifacts",
        "decision_revisions",
        "evidence_refs",
        "experiences",
        "market_rule_versions",
        "model_invocations",
        "paper_fills",
        "research_dossiers",
    )
    for table in immutable_tables:
        op.execute(
            f"CREATE TRIGGER {table}_no_update BEFORE UPDATE ON {table} BEGIN "
            "SELECT RAISE(ABORT, 'append-only table cannot be updated'); END"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_delete BEFORE DELETE ON {table} BEGIN "
            "SELECT RAISE(ABORT, 'append-only table cannot be deleted'); END"
        )
    op.execute(
        "CREATE TRIGGER strategy_versions_no_delete BEFORE DELETE ON strategy_versions BEGIN "
        "SELECT RAISE(ABORT, 'strategy versions cannot be deleted'); END"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS strategy_versions_no_delete")
    for table in (
        "audit_events",
        "cash_ledger",
        "data_artifacts",
        "decision_revisions",
        "evidence_refs",
        "experiences",
        "market_rule_versions",
        "model_invocations",
        "paper_fills",
        "research_dossiers",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_update")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_delete")
    op.execute("DROP TRIGGER IF EXISTS experiences_fts_insert")
    op.execute("DROP TABLE IF EXISTS experiences_fts")
    op.drop_index("ix_position_lots_account_instrument", table_name="position_lots")
    op.drop_table("position_lots")
    op.drop_table("paper_fills")
    op.drop_index("ix_orders_status_created", table_name="order_plans")
    op.drop_table("order_plans")
    op.drop_index("ix_experience_horizon_outcome", table_name="experiences")
    op.drop_table("experiences")
    op.drop_index("ix_decisions_instrument_horizon", table_name="decision_revisions")
    op.drop_table("decision_revisions")
    op.drop_index("ix_dossiers_instrument_created", table_name="research_dossiers")
    op.drop_table("research_dossiers")
    op.drop_table("portfolio_snapshots")
    op.drop_table("model_invocations")
    op.drop_table("intraday_trigger_states")
    op.drop_index("ix_evidence_instrument_published", table_name="evidence_refs")
    op.drop_table("evidence_refs")
    op.drop_table("challenger_reports")
    op.drop_table("cash_ledger")
    op.drop_table("user_feedback")
    op.drop_table("system_settings")
    op.drop_table("strategy_versions")
    op.drop_table("source_health")
    op.drop_table("market_rule_versions")
    op.drop_table("market_calendar_days")
    op.drop_table("lesson_candidates")
    op.drop_index("ix_instruments_investable", table_name="instruments")
    op.drop_table("instruments")
    op.drop_index("ix_artifacts_dataset", table_name="data_artifacts")
    op.drop_table("data_artifacts")
    op.drop_table("audit_events")
    op.drop_index("ix_agent_runs_kind_started", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_table("accounts")
    # ### end Alembic commands ###
